---
format: gfm
---

# QuartoJulia

This small repo is used to build and host the presentation for my JuliaCon 2022 Experience Talk on using Quarto with Julia. The repo itself presents an interesting use case of Quarto, because it is made up almost entirely of Quarto (`.qmd`) documents. For example, the [index.qmd](/index.qmd) file is used to generate the Reveal.js presentation that lives in `docs/` and is hosted on Github Pages ([here](http://www.paltmeyer.com/QuartoJulia/#/title-slide)). Even this README was generated by a Quarto document. 

## Resources 📚

- [Presentation](http://www.paltmeyer.com/QuartoJulia/#/title-slide)
- Related [blog](https://www.paltmeyer.com/blog/posts/julia-and-quarto-a-match-made-in-heaven/) post (hosted on a blog that itself is built with Quarto and involves lots of Julia content). 
- Examples of Julia package documentation I've built with Quarto + `Documenter.jl`:
    1. [`CounterfactualExplanations.jl`](https://www.paltmeyer.com/CounterfactualExplanations.jl/dev/)
    2. [`LaplaceRedux.jl`](https://www.paltmeyer.com/LaplaceRedux.jl/dev/)
- Quarto's own [guide](https://quarto.org/docs/computations/julia.html) to using Quarto with Julia. 